# Generated by Django 5.0.1 on 2024-01-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_age_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interest',
            new_name='Materials',
        ),
    ]
